title: 
url: "SwathingSoap.github.io"
baseurl: "/"

markdown: kramdown
#ins_logo: "./bits-logo.png"

tracking_id: #

footer: no
footer_url: "https://cdn.betterttv.net/emote/5d48374d9728020aca0da45b/3x"
footer_text: "aRolf"

ins_logo: "https://i.imgur.com/G5wQfJW.png"

sass:
    style: compressed
    sass_dir: _sass

nav:
 - name: "Главная "
   link: "index" 
 - name: "Портфолио "
   link: resume
 - name: "Контакты "
   link: "contact"

