title: 
url: "SwathingSoap.github.io"
baseurl: "/"

markdown: kramdown
#ins_logo: "./bits-logo.png"

tracking_id: #

footer: yes
footer_url: "SwathingSoap.github.io"
footer_text: "swathingsoap"

ins_logo: "https://i.imgur.com/G5wQfJW.png"

sass:
    style: compressed
    sass_dir: _sass

nav:
 - name: "Главная "
   link: "index" 
 - name: "Портфолио "
   link: resume
 - name: "Контакты "
   link: "contact"

